apiVersion: v1
kind: Pod
metadata:
  name: env-practice
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: project
      value: roboshop
    - name: component
      value: frontend